### ISSUE TITLE
onDisconnect and onConnecting events

### ISSUE THREAD

**Issue by andzejsw** [konsultaner/connectanum-dart#2]
Is or there will be client connection events like `onDisconnect`, `onConnecting`, `onConnected`. For example depending on those statuses i want to do specific tasks. If onDisconnect is triggered, i would like to call reconnect method etc.
Also for reconnect i am not seeing client.close() option for cases, when i want to close unauthorised client session, but reconnect with client authid,

**Comment by konsultaner** [comment]
It is planned, but not ready yet.

**Comment by konsultaner** [comment]
@andzejsw  i started some reconnect work, but I might have to refactor something. You can give it a try if you want.

**Comment by konsultaner** [comment]
1.0.0.-dev.9 should fix this.

**Comment by andzejsw** [comment]
For me session isn't reconnecting. For example when i disable wifi and enable it again, session is still not connected and doesn't try to connect again.
Also i cant see `onDisconnect`, `onConnecting`, `onConnected` events. There only as far as i see is different reconnect logic. I am creating session this way: 
```
    _session = await client.connect(
        pingInterval: Duration(seconds: 10),
        reconnectTime: Duration(seconds: 10),
        reconnectCount: 100,
    ).first;
```

**Comment by konsultaner** [comment]
> Also i cant see onDisconnect, onConnecting, onConnected events

No I did not add those events. Instead I made `client.connect()` return a stream. For each reconnect the stream pushes a new session object. What you want to do is the following:

```dart
client.connect(
    pingInterval: Duration(seconds: 1),
    reconnectTime: Duration(seconds: 10),
    reconnectCount: 50, // you might get a stack overflow if you have too many
).listen((session) {
    // Do something with your session
});

On some cases the reconnect will only happen when a ping interval fails. So if `pingInterval` is set to 10 seconds. It might take 10 seconds until the client realizes that something went wrong. This highly depends on the transport/plattform you use. The WebSocket:html and the Socket:io works really well, because they provide a better api. The control over WebSocket:io is very poor. So this may work not for all plattforms. In the dartvm (unit tests) I could get a reconnect, but I'm not sure about android/ios.
```

**Comment by andzejsw** [comment]
Tnx. I changed my code, but still wasn't able to catch connection changes and reconnect wasn't happening. `.listen` was triggered only once (only when connected first time) I tested on Android device. My code: 
```
    client.connect(
        pingInterval: Duration(seconds: 1),
        reconnectTime: Duration(seconds: 1),
        reconnectCount: 100,
    ).listen((session) {
      _session = session;
      print('wamp session connection status --- ${session.isConnected()}');
    });
```
I switched off and on wifi on my mobile device.

**Comment by konsultaner** [comment]
what transport did you use? did you (could you) try Socket transport? (which is supported by crossbar)

**Comment by andzejsw** [comment]
I am already using Crossbar socket transport.

**Comment by konsultaner** [comment]
are you on the latest version of connectanum-dart?

**Comment by andzejsw** [comment]
Yes. Actually i checked now and saw, that on wifi disable, `.listen` wasn't triggered. But on enable it was.

**Comment by konsultaner** [comment]
yes, this is the expected behaviour. The next session is pushed to the stream after it has been connected and authenticated. So this behaviour is correct. Did you expect anything else?

**Comment by andzejsw** [comment]
I was expecting, that i know, that ws session is down by some reason, and based on that i would show, that app currently is in offline state. But this could wait and isn't crucial and correct behavior for now can stay.

**Comment by konsultaner** [comment]
I added a `onConnectionLost` beside the `onDisconnect` to the session. This way you should be able to handle it.

client.connect(
    pingInterval: Duration(seconds: 1),
    reconnectTime: Duration(seconds: 10),
    reconnectCount: 50, // you might get a stack overflow if you have too many
).listen((session) {
    session.onConnectionLost.then(() => showReconnectHint())
    session.onDisconnect.then(() => navigateToLogin())
    // Do something with your session
});

**Comment by andzejsw** [comment]
Oh. Big tnx. I will take a look

**Comment by andzejsw** [comment]
I did a same way as in your example, but `onConnectionLost` and `onDisconnect` wasn't called.

**Comment by konsultaner** [comment]
ok, ill write a test later

**Comment by konsultaner** [comment]
I tested it with all transports and it should work now. It did with all my scenarios.
